#!/bin/bash

ICONVBIN='iconv' # path to iconv binary

if [ $# -lt 3 ]
then
	echo "$0 dir from_charset to_charset"
exit
fi

for f in $1/*
	do
	if test -f $f
	then
		echo -e "\nConverting $f"
		mv $f $f.old
		$ICONVBIN -f $2 -t $3 $f.old > $f
		rm $f.old
	else
		echo -e "\nSkipping $f - not a regular file";
	fi
done
