#!/bin/sh
VERT="\\033[1;32m"
NORMAL="\\033[0;39m"
ROUGE="\\033[1;31m"
ROSE="\\033[1;35m"
BLEU="\\033[1;34m"
BLANC="\\033[0;02m"
BLANCLAIR="\\033[1;08m"
JAUNE="\\033[1;33m"
CYAN="\\033[1;36m"

COMPILE=0
make || COMPILE=1

if [ $COMPILE = 1 ]; then
        echo "\n"
        echo "$ROUGE" "Echec de la compilation : commit interdit !" "$NORMAL"
        exit 1
fi

echo "$VERT" "Compilation : OK" "$NORMAL"

# Actions pre-commit
echo ""
